#!/usr/bin/env bash
# This script will transfer a file from one server to another using scp.
#./0-transfer_file README.md 100.26.17.85 ubuntu ~/.ssh/alx
# check if the user has provided the correct number of arguments
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
