#!/usr/bin/env bash
# Change Host Name Of Current Machine
if [ $# -ne 1 ]
then
    echo "Usage: $0 <new-hostname>"
    exit 1
else
    # write hostname to /etc/hostname at loopback address
    sudo sed -i "1s/.*/127.0.0.1 localhost $1/" /etc/hosts
    # change hostname
    sudo hostnamectl set-hostname $1
    
fi