#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it
# Create a backup.sql file
mysqldump -u root -p"$1" --all-databases > backup.sql

# Create a tar.gz archive
tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql