#!/usr/bin/env bash
# This script prints "Hi" 10 times, but only for the 9th iteration, it will print "School" instead of "Hi".

x=0
while [ "$x" -lt 10 ]
do
    echo "Best School"
    if [ "$x" -eq 8 ]
    then
        echo "Hi"
    fi
    x=$((x+1))
done
