#!/usr/bin/env bash
#this Script For Display Clock From 0 to 12

x=0
while [ "$x" -le 12 ]
do
    echo "Hour: $x"
    m=1
    while [ "$m" -le 59 ]
    do
        echo "$m"
        m=$((m+1))
    done
    x=$((x+1))
done
